export const routeNav = [
  "/",
  "/About",
  "/Portfolio",
  // "News",
  "/Contact",
];

export const en = {
  Home: "Home",
  "home.job":
    "Full-stack Developer who loves making friendly interactive and accessible web and mobile interfaces.",
  About: "About",
  "About.name": "Full-stack Developer",
  "About.description":
    "I am a full stack web developer mainly oriented to the frontend with diverse knowledge of current design tools and frameworks. I am a super competitive and proactive person, and a constant student. Every day I try to be better than yesterday, in order to improve myself.",
  "About.button": "Learn More",
  "About.birthday": "Birthday",
  "About.birthday2": "15.06.1999",
  "About.age": "Age",
  "About.age2": "23",
  "About.address": "Address",
  "About.address2": "Guayana City, Bolivar, Venezuela",
  "About.email": "Email",
  "About.email2": "Contact",
  "About.email3": "cesarmiguel199@gmail.com",
  "About.phone": "+58 414 054 1782",
  "About.phone2": "tel:+584140541782",
  "About.study": "Study",
  "About.study2": "UNEG",
  "About.freelance": "Available",
  "About.skills": "Pro Skills",
  "About.skills.1": "React.js",
  "About.skills.2": "JavaScript",
  "About.skills.3": "Node.js",
  "About.skills.4": "Agile Methodologies",
  "About.skills2": "Pre Skills",
  "About.skills2.1": "Creative",
  "About.skills2.2": "TeamWork",
  "About.skills2.3": "Motivation",
  "About.skills2.4": "Positive",
  "About.counter.title1": "Projects Completed",
  "About.counter.title2": "Happy Clients",
  "About.counter.title3": "Lines of Code",
  Portfolio: "Portfolio",
  "Portfolio.title": "Creative Portfolio",
  "Portfolio.client": "Client",
  "Portfolio.category": "Category",
  "Portfolio.share": "Share",
  "Portfolio.date": "Date",
  "Portfolio.client1": {
    portada: require("./img/duosimple.png"),
    image1: require("./img/duosimple-1.png"),
    image2: require("./img/duosimple-2.png"),
    image3: require("./img/duosimple-3.png"),
    image4: require("./img/duosimple-4.png"),
    title: "DuoSimple",
    subTitle: "Inventory Control",
    detail:
      "Local inventory management solution with barcode functions, inventory input and output, graphics and much more.",
    detail2:
      "For the development of this project there was a time limit, which was 2 weeks of work. Electron.js, react.js and node.js were used as main technologies since they were the most viable options for the optimal development of the minimum requirements.",
    clients: "Duoloon",
    category: "Software",
    date: "April 25, 2022",
    share: "",
  },
  "Portfolio.client2": {
    portada: require("./img/taxi.png"),
    image1: require("./img/taxi-1.png"),
    image2: require("./img/taxi-2.png"),
    image3: require("./img/taxi-3.png"),
    image4: require("./img/taxi-4.png"),
    title: "Taxi Tarapaca",
    subTitle: "Sistema de Autocontrol",
    detail:
      "This project was made with the intention of improving the system they already had, because it had many bugs and performance problems. The Tarapaca Taxi Self-Control System is nothing less than a software designed to keep all trips, cars, services and agreements that may be billed by the company up to date.",
    detail2:
      "In addition to that, a completely new backend was built that could support a large amount of data and that the system performance would not be affected. The technologies used for this project were react.js and laravel. A messaging service was also developed to notify both drivers and customers when the service time was approaching.",
    clients: "Taxi Tarapaca",
    category: "Software",
    date: "July 5, 2022",
    share: "",
  },
  Contact: "Contact",
  "Contact.title": "Get in Touch",
  "Contact.name": "Name",
  "Contact.email": "Email",
  "Contact.message": "Message",
  "Contact.button": "Send Message",
  "Contact.empty_notice": "Please Fill Required Fields"
};

export const es = {
  Home: "Inicio",
  "home.job":
    "Desarrollador Full-stack al que le encanta hacer interfaces web y móviles interactivas.",
  About: "Sobre Mi",
  "About.name": "Desarrollador Full-stack",
  "About.description":
    "Soy desarrollador web full stack orientado principalmente al frontend con diversos conocimientos de herramientas de diseños y frameworks actuales. Soy una persona súper competitiva y pro activa, y un constante estudiante. Cada día trato de ser mejor que ayer, para así superarme a mí mismo.",
  "About.button": "Ver Más",
  "About.birthday": "Cumple",
  "About.birthday2": "15-06-1999",
  "About.age": "Edad",
  "About.age2": "23",
  "About.address": "Dirección",
  "About.address2": "Ciudad Guayana, Bolivar, Venezuela",
  "About.email": "Correo",
  "About.email2": "Contacto",
  "About.phone": "+58 414-0541782",
  "About.study": "Estudios",
  "About.study2": "UNEG",
  "About.freelance": "Disponible",
  "About.skills": "Habilidades Profesionales",
  "About.skills2": "Habilidades Previas",
  "About.skills2.1": "Creativo",
  "About.skills2.2": "Trabajo en Equipo",
  "About.skills2.3": "Motivación",
  "About.skills2.4": "Positivismo",
  "About.counter.title1": "Proyectos Completados",
  "About.counter.title2": "Clientes Felices",
  "About.counter.title3": "Lineas de Codigo",
  Portfolio: "Portafolio",
  "Portfolio.title": "Portafolio Creativo",
  "Portfolio.client": "Cliente",
  "Portfolio.category": "Categoria",
  "Portfolio.share": "Compartir",
  "Portfolio.date": "Fecha",
  "Portfolio.client1": {
    portada: require("./img/duosimple.png"),
    image1: require("./img/duosimple-1.png"),
    image2: require("./img/duosimple-2.png"),
    image3: require("./img/duosimple-3.png"),
    image4: require("./img/duosimple-4.png"),
    title: "DuoSimple",
    subTitle: "Control de Inventario",
    detail:
      "Solución de gestión de inventarios local con funciones de códigos de barras, entrada y salidas de inventario, graficas y muchas cosas más.",
    detail2:
      "Para el desarrollo de este proyecto se conto con un limite de tiempo, el cual era de 2 semanas de trabajo. Se utilizo electron.js, react.js y node.js como tecnologias principales ya que fueron las opciones mas viables para el desarrollo optimo de los requerimientos minimos.",
    clients: "Duoloon",
    category: "Software",
    date: "Abril 25, 2022",
    share: "",
  },
  "Portfolio.client2": {
    portada: require("./img/taxi.png"),
    image1: require("./img/taxi-1.png"),
    image2: require("./img/taxi-2.png"),
    image3: require("./img/taxi-3.png"),
    image4: require("./img/taxi-4.png"),
    title: "Taxi Tarapaca",
    subTitle: "Sistema de Autocontrol",
    detail:
      "Este proyecto se hizo con la intencion de mejorar el sistema que ellos ya tenian, debido a que el mismo presentaba muchos bugs y problemas de rendimiento. El Sistema de Autocontrol de Taxi Tarapaca no es nada menos que un sofware diseñado para mantener al dia todos los viajes, coches, servicios y convenios que puedan ser facturados por la empresa.",
    detail2:
      "Adicionalmente a eso se construyo un backend totalmente nuevo que pudiera soportar muchisima cantidad de datos y que el rendimiento del sistema no se viera afectado, Las tecnologias usadas para este proyecto fueron react.js y laravel. Tambien se elaboró un servicio de mensajeria para asi notificar tanto a los conductores como a los clientes cuando se acercara la hora del servicio.",
    clients: "Taxi Tarapaca",
    category: "Software",
    date: "Julio 5, 2022",
    share: "",
  },
  Contact: "Contacto",
  "Contact.title": "Ponerse en Contacto",
  "Contact.name": "Nombre",
  "Contact.email": "Correo",
  "Contact.message": "Mensaje",
  "Contact.button": "Enviar Mensaje",
  "Contact.empty_notice": "Por favor complete todos los campos requeridos"
};

export const idiom = (language, title) => {
  return language === "en" ? en[title] : es[title];
};
